<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>a2n.Hangfire.Dashboard.SqlServer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.*" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\a2n.Hangfire.Dashboard\a2n.Hangfire.Dashboard.csproj" />
  </ItemGroup>
</Project>
